### ISSUE TITLE
Request for kind help

### ISSUE THREAD

**Issue by ebamule** [khliland/plsVarSel#3]
# Dear Sir,
I was trying to use "plsVarSel" package. I installed it and when I am loading with library;

# Install development version from GitHub  
devtools::install_github("khliland/plsVarSel")

library("plsVarSel")

I am receiving an error message as follows: please any way out of this problem. thanks so much.

Registered S3 methods overwritten by 'rgl':
  method               from
  knit_print.rglId         
  knit_print.rglOpen3d     
  sew.rglRecordedplot      
Error in dyn.load(dynlib <- getDynlib(dir)) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/rgl/libs/rgl.so, 0x0006): Library not loaded: '/opt/X11/lib/libGLU.1.dylib'
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/rgl/libs/rgl.so'
  Reason: tried: '/opt/X11/lib/libGLU.1.dylib' (no such file), '/usr/local/lib/libGLU.1.dylib' (no such file), '/usr/lib/libGLU.1.dylib' (no such file)
Error: package or namespace load failed for ‘plsVarSel’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: rgl.init(initValue, onlyNULL)
  error: OpenGL is not available in this build
In addition: Warning messages:
1: 	Loading rgl's DLL failed. 
	This build of rgl depends on XQuartz, which failed to load.
 See the discussion in https://stackoverflow.com/a/66127391/2554330 
2: Trying without OpenGL...

**Comment by khliland** [comment]
Dear ebamule,

Unfortunately the current version of _plsVarSel_ depends on the _rgl_ package because of its import of `mult.chart()` from the _MSQC_ package. It seems your system has some trouble with XQuartz (guessing for a Mac). XQuartz is working fine on my Mac, but typically needs a full reboot after installation to fully work. Could you check that plotting with XQuartz works as expected, e.g., opening a _terminal_, writing `R`, and then plotting something simple like `plot(1)`.

Regards,
Kristian

**Comment by ebamule** [comment]
Thanks so much for your swift reply. Following your suggestion, I managed
to run it.

**Comment by khliland** [comment]
Hi Eba!

In some cases, e.g., when having many variables, using the formula interface is easier if you group your variables together. For instance, if you have a matrix of microbial data `micro` and a response vector `stress`, you can make a `list` or `data.frame` where the matrix can be referred to as a single entity:
```
micro_list <- list(y = stress, X = micro)
micro_frame <- data.frame(y = stress, X = I(micro))
```
Here, the "as is" operator `I()` keeps the matrix accessible as `micro_frame$X`. I usually use the `data.frame` version myself. This means you can later use PLS, e.g., something like this:
```
micro_model <- plsr(y ~ X, data = micro_frame, ncomp = 10, validation = "CV", segments = 5)
```
... and then methods from the plsVarSel package with this model.

Hope this helps!
Kristian

**Comment by ebamule** [comment]
Appreciated your support. 🙏🙏
